require 'factory_girl'
require File.dirname(__FILE__) + '/../../spec/factories/game.rb'
require File.dirname(__FILE__) + '/../../spec/factories/player.rb'
require File.dirname(__FILE__) + '/../../spec/factories/team.rb'
require File.dirname(__FILE__) + '/../../spec/factories/customer.rb'
